<div class="row">
<center>
<img src="<?= $this->basePath() ?>/img/fancyheader.gif">
<img src="<?= $this->basePath() ?>/img/fancyheader.jpg">
</center>
    <h1>Welkom</h1>

    <p>
        <?= $this->translate('Welcome to the website of Study association GEWIS, the study association of
        the department of Mathematics & Computer Science of the Eindhoven University of Technology.') ?>
    </p>
    <p>
        <?= sprintf($this->translate('GEWIS means Community of Mathematics and Computer Science Students
            (or in Dutch: GEmeenschap van Wiskunde en Informatica Studenten) and was founded in 1982.
            On this website you can find out %s and %s.'),
                '<a href="' . $this->url('home/page',
                    ['category' => 'vereniging']) . '">' . $this->translate('who we are') . '</a>',
                '<a href="' . $this->url('activity') . '">' . $this->translate('what we do') . '</a>')
        ?>
    </p>

    <h3><?= $this->translate('Agenda') ?></h3>
    <div class="list-group">
        <?php foreach ($activities as $activity): ?>
            <a class="list-group-item agenda-item"
               href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
            <span class="badge">
                <span class="text-lowercase small"><?= $activity->getBeginTime()->format('M') ?>
                    &nbsp;</span>
                <span><?= $activity->getBeginTime()->format('d') ?></span>
            </span>

                <?= $activity->getName(); ?>

            </a>
        <?php endforeach; ?>
    </div>

    <p>
        <?= sprintf(
            $this->translate('Donderdags is er %sborrel%s van 16.30 tot 19.00 uur.'),
            '<a href="~bac">',
            '</a>'
        )
        ?>
    </p>

    <div class="col-xs-8">
        <a href="<?= $this->url('activity') ?>">
            <?= $this->translate('Complete agenda') ?>
            <span class="glyphicon glyphicon-arrow-right"></span>
        </a>
    </div>
    <div class="col-xs-4">
        <a href="https://www.google.com/calendar/embed?src=v23gq10ij44fhdsfdof1s613ak%40group.calendar.google.com&gsessionid=OK"
           title="<?= $this->translate('Google Calendar') ?>">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;iCal
        </a>
    </div>

</div>

    <div class="panel-group panel-group-horizontal">
        <div class="panel">
            <div class="panel-heading">
                <h3><?= $this->translate('News') ?></h3>
            </div>
        </div>
        <?php foreach ($news as $item): ?>
            <div class="panel">
                <div class="panel-heading">
                    <h4>
                        <?php
                        // TODO: Fix design and URLs
                        $lang = $this->plugin('translate')->getTranslator()->getLocale();
                        if ($item instanceof \Activity\Model\Activity) {
                            echo ($lang === 'en') ? $item->getNameEn() : $item->getName();
                        } else {
                            echo ($lang === 'en') ? $item->getEnglishTitle() : $item->getDutchTitle();
                        }
                        ?>
                    </h4>
                </div>
                <div class="panel-body">
                    <p>
                        <?php
                        if ($item instanceof \Activity\Model\Activity) {
                            echo ($lang === 'en') ? $item->getDescriptionEn() : $item->getDescription();
                        } else {
                            echo ($lang === 'en') ? $item->getEnglishContent() : $item->getDutchContent();
                        }
                        ?>
                    </p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3><?= $this->translate('Birthdays today!') ?></h3>
                    </div>
                    <div class="panel-body">
                        <?php if (!is_null($birthdayTag)): ?>
                            <div class="thumb">
                                <a class="thumbnail" href="<?= $this->url('photo/photo',
                                    ['photo_id' => $birthdayTag->getPhoto()->getId()]); ?>">
                                    <img class="img-responsive"
                                         src="<?= $this->fileUrl($birthdayTag->getPhoto()->getLargeThumbPath()) ?>"
                                         alt="">
                                </a>
                            </div>
                        <?php endif; ?>
                        <?php if (!empty($birthdays)): ?>
                            <ul>
                                <?php foreach ($birthdays as $birthday): ?>
                                    <li><?= sprintf($this->translate('%s wil be %s years old today!'),
                                            $birthday['member']->getFullName(),
                                            $birthday['age']) ?></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <?= $this->translate('Nobody seems to have a birthday today, be the first one!') ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3><?= $this->translate('Poll') ?></h3>
                    </div>
                    <?php if (isset($poll['poll'])): ?>
                        <div class="panel-body">
                            <?= $this->partial('partial/poll.phtml', [
                                'poll' => $poll['poll'],
                                'canVote' => $poll['canVote'],
                                'userVote' => $poll['userVote'],
                                'showResults' => false
                            ]) ?>
                        </div>
                        <div class="panel-footer">
                            <a href="<?= $this->url('poll') ?>"><?= $this->translate('View the results') ?></a>
                        </div>
                    <?php else: ?>
                        <div class="panel-footer">
                            <?= $this->translate('There currently is no poll.'); ?>
                            <a href="<?= $this->url('poll/request') ?>"><?= $this->translate('Request a poll') ?></a> <?= $this->translate('or') ?>
                            <a href="<?= $this->url('poll/history') ?>"><?= $this->translate('view old polls') ?></a>.
                        </div>
                    <?php endif; ?>

                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3><?= $this->translate('Photo of the week') ?></h3>
                    </div>
                    <div class="panel-body">
                        <?php if (!is_null($weeklyPhoto)): ?>
                            <div class="thumb">
                                <a class="thumbnail" href="<?= $this->url('photo/photo',
                                    ['photo_id' => $weeklyPhoto->getPhoto()->getId()]); ?>">
                                    <img class="img-responsive"
                                         src="<?= $this->fileUrl($weeklyPhoto->getPhoto()->getLargeThumbPath()) ?>"
                                         alt="">
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
