<?php
$lang = $this->plugin('translate')->getTranslator()->getLocale();
?>

<table style="border-collapse: separate; border-spacing: 5px">
    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <a href="<?= $this->url('home') ?>">
                HomePage
            </a>
        </td>
    </tr>

    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <div class="dropdown dropdown-hover">
                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?= $this->translate('Association') ?>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?= $this->url('home/page', ['category' => 'vereniging']) ?>"><?= $this->translate('Association') ?></a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'av']) ?>"><?= $this->translate('General Meeting') ?></a></li>
                    <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'bestuur']) ?>"><?= $this->translate('Board 2015/2016') ?></a></li>
                    <li><a href="<?= $this->url('home/committee_list') ?>"><?= $this->translate('Committees') ?></a></li>
                    <li><a href="<?= $this->url('home/fraternity_list') ?>"><?= $this->translate('Fraternities') ?></a></li>
                    <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'lied']) ?>"><?= $this->translate('GEWIS song') ?></a></li>
                    <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'statuten']) ?>"><?= $this->translate('Regulations') ?></a></li>
                    <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'contact']) ?>"><?= $this->translate('Contact') ?></a></li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <div class="dropdown dropdown-hover">
                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?= $this->translate('Companies') ?>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?= $this->url('company') ?>"><?= $this->translate('Companies') ?></a></li>
                    <li role="separator" class="divider"></li>
                    <?php if (!is_null($this->featuredCompanyPackage())): ?>
                        <li>
                            <a href="<?= $this->url('company/spotlight') ?>">
                                <span class="glyphicon glyphicon-star"></span>
                                <?= $this->translate('Featured') ?>:
                                <?= $this->featuredCompanyPackage()->getCompany()->getName() ?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <li><a href="<?= $this->url('company/jobList') ?>"><?= $this->translate('Jobs') ?></a></li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <a href="<?= $this->url('education') ?>">
                <?= $this->translate('Education') ?>
            </a>
        </td>
    </tr>

    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <div class="dropdown dropdown-hover">
                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?= $this->translate('Activities') ?>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?= $this->url('activity') ?>"><?= $this->translate('Activity') ?></a></li>
                    <li role="separator" class="divider"></li>
                    <?php if ($this->acl('activity_acl')->isAllowed('activity', 'create')): ?>
                        <li><a href="<?= $this->url('activity/create') ?>"> <?= $this->translate('Create an activity') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <div class="dropdown dropdown-hover">
                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?= $this->translate('Photos') ?>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?= $this->url('photo') ?>"><?= $this->translate('Photos') ?></a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="<?= $this->url('photo/weekly') ?>"><?= $this->translate('Photo of the week') ?></a></li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <a href="<?= $this->url('lang', ['lang' => 'en']) ?>">
                <span class="flag-icon flag-icon-en" style="background-image: url('<?= $this->basePath() ?>/img/en.svg');"></span> English
            </a>
        </td>
    </tr>
    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <a href="<?= $this->url('lang', ['lang' => 'nl']) ?>">
                <span class="flag-icon flag-icon-nl" style="background-image: url('<?= $this->basePath() ?>/img/nl.svg');"></span> Nederlands
            </a>
        </td>
    </tr>


    <?php if (null != $this->identity()): ?>
    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <a href="<?= $this->url('member') ?>">
                <?= $this->translate('Members') ?>
            </a>
        </td>
    </tr>
    <?php endif ?>


    <tr>
        <td style="border: 1px solid black; padding: 4px; background-color: rgb(255,255,204);">
            <?php if (null === $this->identity()): ?>
            <div class="dropdown dropdown-hover">
                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?= $this->translate('Login') ?>
                </a>
                <ul class="dropdown-menu dropdown-login">
                    <form action="<?= $this->url('user') ?>" method="post">
                        <div class="form-group">
                            <input type="text" name="login" class="form-control" placeholder="<?= $this->translate('Membership number or email address') ?>" />
                        </div>
                        <div class="form-group">
                            <input type="password" name="password" class="form-control" placeholder="<?= $this->translate('Password') ?>">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block"><?= $this->translate('Login') ?></button>
                        <p><?= $this->translate('Or go to the') ?> <a href="<?= $this->url('user/default', ['action' => 'register']) ?>"><?= $this->translate('registration page') ?></a></p>

                        <input type="hidden" name="redirect" value="<?= $_SERVER['REQUEST_URI'] ?>">
                    </form>
                </ul>
            </div>
            <?php else: ?>
            <?php $member = $this->identity()->getMember() ?>
            <div class="dropdown dropdown-hover">
                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?= $member->getFirstName() ?>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?= $this->url('member/self') ?>"><?= $this->translate('My information') ?></a></li>
                    <li><a href="https://gewis.nl/susos/account/websitelogin.php"><?= $this->translate('SuSOS') ?></a></li>
                    <li><a href="<?= $this->url('user/default', ['action' => 'password']) ?>"><?= $this->translate('Change password') ?></a></li>
                    <?php if ($this->acl('decision_acl')->isAllowed('organ', 'edit')): ?>
                        <li><a href="<?= $this->url('admin') ?>"><?= $this->translate('Admin') ?></a></li>
                    <?php endif; ?>
                    <li><a href="<?= $this->url('user/default', [
                            'action' => 'logout'
                        ]) ?>"><?= $this->translate('Logout') ?></a></li>
                </ul>
            </div>
            <?php endif ?>
        </td>
    </tr>

</table>
