<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('GEWIS HomePage'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath() . '/css/gewis-theme.css') ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', ['conditional' => 'lt IE 9',])
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', ['conditional' => 'lt IE 9',])
            ->prependFile($this->basePath() . '/js/url-helper.js')
        ; ?>

    </head>
    <body background="<?= $this->basePath() ?>/img/fancybg.gif">

    <table border="0">
        <tr>
            <td>
                <a href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath() ?>/img/anilogo.gif" alt="<?= $this->translate('GEWIS Logo') ?>">
                </a>
            </td>
            <td>
<center>
<font size="+3"><?= $this->translate('Studievereniging') ?></font>
    <br>
    <font size="+5" color="#FF0000">GEWIS</font>
</center>
            </td>
            <td width="200">
                <a href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath() ?>/img/anilogo.gif" alt="<?= $this->translate('GEWIS Logo') ?>">
                </a>
            </td>
        </tr>

        <tr>
            <td valign=top width="200">
                <?= $this->partial('partial/fancy-nav.phtml') ?>
            </td>
            <td valign=top colspan=2>
                <div class="content-container">
                    <?php $viewModel = current($this->viewModel()->getCurrent()->getChildren());
                        if(strstr($viewModel->getTemplate(), 'admin')) {
                            echo $this->partial('partial/admin-nav.phtml', ['content' => $this->content]);
                        } else {
                            echo $this->content;
                        }
                     ?>
                </div>
            </td>
        </tr>

        <tr>
            <td colspan=3>
                <?= $this->partial('partial/footer.phtml') ?>

                <?= $this->inlineScript() ?>
                <script>
                    <?php foreach($this->scriptUrl()->getUrls() as $name => $url): ?>
                    URLHelper.addUrl('<?= $name ?>', '<?= urldecode($url) ?>');
                    <?php endforeach; ?>
                </script>
            </td>
        </tr>
    </table>
    </body>
</html>
